//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Types
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalendarEntry
    {
        public int Id { get; set; }
        public Day Day { get; set; }
        public string StartHour { get; set; }
        public string EndHour { get; set; }
        public int CourseId { get; set; }
    
        public virtual Course Course { get; set; }
    }
}
